<font color='blue'><h1>Assignment 3: "Gaurav Raut 2038584/h1></font>

In [1]:
# Multiple Linear Regression

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 3] = labelencoder.fit_transform(X[:, 3])
onehotencoder = OneHotEncoder(categorical_features = [3])
X = onehotencoder.fit_transform(X).toarray()

# Avoiding the Dummy Variable Trap
X = X[:, 1:]

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

C:\Users\HelpEase\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\HelpEase\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [2]:
np.set_printoptions(suppress = True)
print(X)

[[     0.        1.   165349.2  136897.8  471784.1 ]
 [     0.        0.   162597.7  151377.59 443898.53]
 [     1.        0.   153441.51 101145.55 407934.54]
 [     0.        1.   144372.41 118671.85 383199.62]
 [     1.        0.   142107.34  91391.77 366168.42]
 [     0.        1.   131876.9   99814.71 362861.36]
 [     0.        0.   134615.46 147198.87 127716.82]
 [     1.        0.   130298.13 145530.06 323876.68]
 [     0.        1.   120542.52 148718.95 311613.29]
 [     0.        0.   123334.88 108679.17 304981.62]
 [     1.        0.   101913.08 110594.11 229160.95]
 [     0.        0.   100671.96  91790.61 249744.55]
 [     1.        0.    93863.75 127320.38 249839.44]
 [     0.        0.    91992.39 135495.07 252664.93]
 [     1.        0.   119943.24 156547.42 256512.92]
 [     0.        1.   114523.61 122616.84 261776.23]
 [     0.        0.    78013.11 121597.55 264346.06]
 [     0.        1.    94657.16 145077.58 282574.31]
 [     1.        0.    91749.16 114175.79 2949

In [3]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Predicting the Test set results
y_pred = regressor.predict(X_test)

In [4]:
y_pred

array([103015.20159796, 132582.27760815, 132447.73845175,  71976.09851258,
       178537.48221056, 116161.24230166,  67851.69209676,  98791.73374687,
       113969.43533013, 167921.06569551])

In [5]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])